// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWSSdb2OhsuTXnlGqSv0owFmDsCiP-i1A',
    appId: '1:383226017741:web:2334cf886c6af8ec543684',
    messagingSenderId: '383226017741',
    projectId: 'newslens-7f292',
    authDomain: 'newslens-7f292.firebaseapp.com',
    storageBucket: 'newslens-7f292.firebasestorage.app',
    measurementId: 'G-ZG34K2C9TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbDiBs9yOJ3J4ml8foeTYEWNHw3RcOJUI',
    appId: '1:383226017741:android:ddc395f5ed20218a543684',
    messagingSenderId: '383226017741',
    projectId: 'newslens-7f292',
    storageBucket: 'newslens-7f292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgbFNWVI8eo5hW0cSMdQ4sdAC613ug1UE',
    appId: '1:383226017741:ios:00a6413553522f3d543684',
    messagingSenderId: '383226017741',
    projectId: 'newslens-7f292',
    storageBucket: 'newslens-7f292.firebasestorage.app',
    iosBundleId: 'com.example.newsLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgbFNWVI8eo5hW0cSMdQ4sdAC613ug1UE',
    appId: '1:383226017741:ios:00a6413553522f3d543684',
    messagingSenderId: '383226017741',
    projectId: 'newslens-7f292',
    storageBucket: 'newslens-7f292.firebasestorage.app',
    iosBundleId: 'com.example.newsLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWSSdb2OhsuTXnlGqSv0owFmDsCiP-i1A',
    appId: '1:383226017741:web:2bdaa47fa5852295543684',
    messagingSenderId: '383226017741',
    projectId: 'newslens-7f292',
    authDomain: 'newslens-7f292.firebaseapp.com',
    storageBucket: 'newslens-7f292.firebasestorage.app',
    measurementId: 'G-4G5FKCYLPM',
  );
}
